# $FreeBSD: head/graphics/php72m-exif/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-exif

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
