# $FreeBSD: head/security/php56m-openssl/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-openssl

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
