# $FreeBSD: head/converters/php56m-iconv/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-iconv

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
