# $FreeBSD: branches/2019Q1/www/cgi_php56m/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	devel
PKGNAMEPREFIX=	cgi_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	lang/php56m
MASTERDIR=	${.CURDIR}/../../${PHP_PORT}

OPTIONS_DEFAULT=CGI

CGI_DESC=   Build CGI version PHP 5.6

.include "${MASTERDIR}/Makefile"
