# $FreeBSD: head/ftp/php56m-curl/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	ftp

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-curl

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
