# $FreeBSD: branches/2019Q1/www/embed_php56m/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	devel
PKGNAMEPREFIX=	embed_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	lang/php56m
MASTERDIR=	${.CURDIR}/../../${PHP_PORT}

OPTIONS_DEFAULT=EMBED

EMBED_DESC=   Build embedded library PHP 5.6

.include "${MASTERDIR}/Makefile"
