# $FreeBSD: head/www/cli_php73m/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	devel
PKGNAMEPREFIX=	cli_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	php73m
MASTERDIR=	${.CURDIR}/../${PHP_PORT}

OPTIONS_DEFAULT=CLI

CLI_DESC=   Use CLI interface to PHP 7.3

.include "${MASTERDIR}/Makefile"
