# $FreeBSD: branches/2019Q1/databases/php56m-pdo_mysql/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-pdo_mysql

.include "${MASTERDIR}/Makefile"
