# $FreeBSD: head/graphics/php72m-gd/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-gd

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"

LIB_DEPENDS+=	libgd.so:graphics/gd
