# $FreeBSD: head/textproc/php72m-xmlwriter/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-xmlwriter

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
