# $FreeBSD: head/security/php73m-sodium/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-sodium

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
