# $FreeBSD: head/sysutils/php56m-posix/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	sysutils

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-posix

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
