# $FreeBSD: head/databases/php72m-pdo_sqlite/Makefile 475229 2018-07-24 08:44:32Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-pdo_sqlite

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
