# $FreeBSD: head/misc/php72m-calendar/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	misc

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-calendar

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
