# $FreeBSD: head/textproc/php73m-pspell/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	textproc

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-pspell

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
