# $FreeBSD: head/databases/php73m-pdo_odbc/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-pdo_odbc

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
