# $FreeBSD: head/www/php73m-opcache/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-opcache

TEST_TARGET=    test

USES=	phpm:zend,noflavors

.include "${MASTERDIR}/Makefile"
