# $FreeBSD: head/devel/php73m-readline/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-readline

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
