# $FreeBSD: branches/2019Q1/databases/php56m-sybase_ct/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-sybase_ct

.include "${MASTERDIR}/Makefile"
