# $FreeBSD: head/www/phpdbg_php73/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	devel
PKGNAMEPREFIX=	phpdbg_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	php73m
MASTERDIR=	${.CURDIR}/../${PHP_PORT}

OPTIONS_DEFAULT=PHPDBG

PHPDBG_DESC=   Use PHPDBG debugger to PHP 7.3

.include "${MASTERDIR}/Makefile"
