# $FreeBSD: head/www/embed_php73m/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	devel
PKGNAMEPREFIX=	embed_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	php73m
MASTERDIR=	${.CURDIR}/../${PHP_PORT}

OPTIONS_DEFAULT=EMBED

EMBED_DESC=   Use EMBED PHP 7.3

.include "${MASTERDIR}/Makefile"
