# $FreeBSD: branches/2019Q1/databases/php56m-pdo_pgsql/Makefile 487272 2018-12-12 01:35:33Z gerald $

PORTREVISION=	1
CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-pdo_pgsql

.include "${MASTERDIR}/Makefile"
