# $FreeBSD: head/www/cli_php72m/Makefile 454302 2017-11-16 10:48:48Z tz $

CATEGORIES=	devel
PKGNAMEPREFIX=	cli_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	php72m
MASTERDIR=	${.CURDIR}/../${PHP_PORT}

OPTIONS_DEFAULT=CLI

CLI_DESC=   Build CLI version PHP 7.2

.include "${MASTERDIR}/Makefile"
