# $FreeBSD: head/converters/php72m-mbstring/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-mbstring

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
