# $FreeBSD: head/www/fpm_php72m/Makefile 454302 2017-11-16 10:48:48Z tz $

CATEGORIES=	devel
PKGNAMEPREFIX=	fpm_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	php72m
MASTERDIR=	${.CURDIR}/../${PHP_PORT}

OPTIONS_DEFAULT=FPM

FPM_DESC=   Build FPM version PHP 7.2

.include "${MASTERDIR}/Makefile"
