# $FreeBSD: head/net/php72m-soap/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-soap

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
