# $FreeBSD: head/security/php73m-hash/Makefile 482202 2018-10-16 05:14:42Z joneum $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-hash

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
