# $FreeBSD: branches/2019Q1/security/php56m-mcrypt/Makefile 422652 2016-09-23 08:26:44Z tz $

CATEGORIES=	security

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-mcrypt

.include "${MASTERDIR}/Makefile"
