# $FreeBSD: head/mail/php72m-imap/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-imap

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
