# $FreeBSD: head/archivers/php73m-zip/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-zip

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
