# $FreeBSD: head/mail/php73m-imap/Makefile 485647 2018-11-23 10:28:43Z joneum $

CATEGORIES=	mail

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-imap

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
