# $FreeBSD: head/math/php73m-bcmath/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-bcmath

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
