# $FreeBSD: head/www/phpdbg_php72m/Makefile 454302 2017-11-16 10:48:48Z tz $

CATEGORIES=	devel
PKGNAMEPREFIX=	phpdbg_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	php72m
MASTERDIR=	${.CURDIR}/../${PHP_PORT}

OPTIONS_DEFAULT=PHPDBG

PHPDBG_DESC=   Interactive PHP debugger PHP 7.3

.include "${MASTERDIR}/Makefile"
