# $FreeBSD: head/devel/php56m-sysvshm/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-sysvshm

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
