# $FreeBSD: head/www/php56m-opcache/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-opcache

TEST_TARGET=	test

USES=		phpm:zend,noflavors

.include "${MASTERDIR}/Makefile"
