# $FreeBSD: branches/2019Q1/www/fpm_php56m/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	devel
PKGNAMEPREFIX=	fpm_

MAINTAINER=	zevs5@zevs5.ru

PHP_PORT=	lang/php56m
MASTERDIR=	${.CURDIR}/../../${PHP_PORT}

OPTIONS_DEFAULT=FPM

FPM_DESC=   Build FPM version PHP 5.6

.include "${MASTERDIR}/Makefile"
