# $FreeBSD: head/math/php72m-gmp/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	math

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-gmp

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
