# $FreeBSD: head/www/php72m-tidy/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-tidy

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
