# $FreeBSD: head/graphics/php73m-gd/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-gd

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"

LIB_DEPENDS+=	libgd.so:graphics/gd
