# $FreeBSD: branches/2019Q1/databases/php56m-pdo_firebird/Makefile 480602 2018-09-24 12:01:39Z ale $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-pdo_firebird

.include "${MASTERDIR}/Makefile"
