# $FreeBSD: head/net/php56m-sockets/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-sockets

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
