# $FreeBSD: head/archivers/php72m-zlib/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	archivers

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-zlib

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
