# $FreeBSD: head/databases/php56m-dba/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php56m

PKGNAMESUFFIX=	-dba

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
