# $FreeBSD: head/databases/php73m-pgsql/Makefile 507979 2019-08-03 18:29:39Z tz $

CATEGORIES=	databases

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-pgsql

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
