# $FreeBSD: head/misc/php73mcalendar/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	misc

MASTERDIR=	${.CURDIR}/../../lang/php73m

PKGNAMESUFFIX=	-calendar

TEST_TARGET=    test

.include "${MASTERDIR}/Makefile"
