# $FreeBSD: head/net-mgmt/php72m-snmp/Makefile 481525 2018-10-08 08:52:51Z tz $

CATEGORIES=	net-mgmt

MASTERDIR=	${.CURDIR}/../../lang/php72m

PKGNAMESUFFIX=	-snmp

TEST_TARGET=	test

.include "${MASTERDIR}/Makefile"
